package week3;
/*
3.36.1 Net Operating Income for an Investment Property.
easy
|
30 min
|
Share
Description: Net Operating Income (NOI) is an important metric for real estate investors. It represents the income generated by a property, minus the expenses associated with owning and operating it. Your task is to write a method that will take in three inputs, rental income, expenses, and vacancy rate, and then calculate the net operating income for an investment property. Inputs:

Monthly Rental Income: The total amount of money generated by renting out the property per month.

Expenses: The total expenses associated with owning and operating the property, such as property taxes, insurance, maintenance costs, and utilities.

Vacancy Rate: The percentage of time that the property is expected to be unoccupied or "vacant" during the year.

Vacancy rate refers to the percentage of time that a rental property is expected to be unoccupied or "vacant" during a given period of time. For example, if a property is expected to be vacant for two months out of the year, the vacancy rate would be 16.7% (2/12 months)
Output:

Net Operating Income: The income generated by the property, minus the expenses associated with owning and operating it.
Task: Your task is to write a static method called netOperatingIncome() that will take in three double params, monthly rental income, expenses, and vacancy rate, and then calculate the net operating income for an investment property. Expected Result:

plain
Copy code
Input: rentalIncome = 5000.0, expenses = 2500.0, vacancyRate = 10.0
Calculation: effectiveRentalIncome = 5000 * (100 - 10) / 100 = 4500.0
              netOperatingIncome = 4500 - 2500 = 2000.0
Output: 2000.0

Input: rentalIncome = 10000.0, expenses = 3000.0, vacancyRate = 5.0
Calculation: effectiveRentalIncome = 10000 * (100 - 5) / 100 = 9500.0
              netOperatingIncome = 9500 - 3000 = 6500.0
Output: 6500.0

Input: rentalIncome = 7500.0, expenses = 4000.0, vacancyRate = 15.0
Calculation: effectiveRentalIncome = 7500 * (100 - 15) / 100 = 6375.0
              netOperatingIncome = 6375 - 4000 = 2375.0
Output: 2375.0
 */
//write your static method here. No need to add Main class or main method.

public class Week3_36_1_NetOperatingIncomeForAnInvestmentProperty {
    public static void main(String[] args) {

        double result1 = netOperatingIncome(5000.0, 2500.0, 10.0);
        System.out.println(result1);

        double result2 = netOperatingIncome(10000.0, 3000.0, 5.0);
        System.out.println(result2);

        double result3 = netOperatingIncome(7500.0, 4000.0, 15.0);
        System.out.println(result3);

    }

    public static double netOperatingIncome(double rentalIncome, double expenses, double vacancyRate) {
        double effectiveRentalIncome = rentalIncome * (100 - vacancyRate) /100;

        return effectiveRentalIncome - expenses;
    }

}
